---
- include_tasks: setup-debian.yml
  when: ansible_os_family == 'Debian'

- name: Install packer software.
  ansible.builtin.apt:
    name: "packer={{ packer_version }}"
    state: present
    update_cache: true
